import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Gradia Inc. collects, uses, discloses, and protects information when you use our AI voice agent platform, website, and services.",
};

const body =
  "font-sans text-base font-normal leading-[1.8] text-[#6B7280]";
const h2 =
  "mt-12 border-b border-[#E5E7EB] pb-3 font-sans text-[22px] font-bold leading-snug text-[#0A0A0A]";
const list = `${body} ml-6 list-disc space-y-2 [&_li]:pl-1`;

export default function PrivacyPage() {
  return (
    <div className="bg-[#FFFFFF] font-sans">
      <article className="mx-auto max-w-[680px] px-4 py-[80px] sm:px-6">
        <p className="text-xs font-medium uppercase tracking-[0.15em] text-[#3B6EF5]">
          Legal
        </p>
        <h1 className="mt-4 text-[clamp(2rem,4vw+1rem,48px)] font-bold leading-tight tracking-[-0.02em] text-[#0A0A0A]">
          Privacy Policy
        </h1>
        <p className={`mt-4 text-sm text-[#6B7280]`}>
          Last updated: April 23, 2026
        </p>

        <div className="mt-10 space-y-6 [&>p]:mb-0">
          <p className={body}>
            Gradia Inc. (&quot;Gradia,&quot; &quot;we,&quot; &quot;us,&quot; or
            &quot;our&quot;) operates an AI voice agent platform that helps
            businesses manage inbound communications, lead capture, and
            appointment booking. This Privacy Policy explains how we collect, use,
            disclose, and protect information when you use our services, visit
            our website at{" "}
            <Link
              href="https://trygradia.com"
              className="text-[#3B6EF5] underline underline-offset-2 hover:opacity-90"
            >
              trygradia.com
            </Link>
            , or interact with us in any way.
          </p>
          <p className={body}>
            Please read this policy carefully. By using our services, you agree
            to the practices described here.
          </p>
        </div>

        <h2 className={h2}>1. Information We Collect</h2>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Information you provide directly:
          </strong>
        </p>
        <ul className={`${list} mt-3`}>
          <li>
            Name, email address, phone number, and company details when you
            register or book a demo
          </li>
          <li>Billing and payment information when you subscribe to a plan</li>
          <li>
            Communications you send to us via email, contact forms, or support
            channels
          </li>
        </ul>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Information collected through our platform:
          </strong>
        </p>
        <ul className={`${list} mt-3`}>
          <li>
            Call recordings and transcripts generated by the Gradia voice agent
            on behalf of our clients
          </li>
          <li>
            Lead information captured during AI-handled conversations, including
            names, contact details, and appointment data
          </li>
          <li>
            Usage data including how clients and their customers interact with
            the platform
          </li>
        </ul>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Information collected automatically:
          </strong>
        </p>
        <ul className={`${list} mt-3`}>
          <li>
            Log data including IP address, browser type, pages visited, and time
            spent on site
          </li>
          <li>
            Cookies and similar tracking technologies (see Section 7)
          </li>
          <li>
            Device information including operating system and browser version
          </li>
        </ul>

        <h2 className={h2}>2. How We Use Your Information</h2>
        <p className={`${body} mt-6`}>We use the information we collect to:</p>
        <ul className={`${list} mt-3`}>
          <li>Provide, operate, and improve the Gradia platform and services</li>
          <li>
            Process transactions and send related information including
            confirmations and invoices
          </li>
          <li>
            Send administrative communications such as service updates, security
            alerts, and support messages
          </li>
          <li>Respond to enquiries and provide customer support</li>
          <li>
            Send marketing communications where you have opted in to receive them
          </li>
          <li>
            Analyse usage patterns to improve our product and user experience
          </li>
          <li>Comply with legal obligations and enforce our terms</li>
        </ul>
        <p className={`${body} mt-6`}>
          We do not sell your personal information to third parties.
        </p>

        <h2 className={h2}>3. How We Share Your Information</h2>
        <p className={`${body} mt-6`}>
          We may share your information in the following circumstances:
        </p>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Service providers:
          </strong>{" "}
          We work with trusted third-party vendors who assist us in operating our
          platform, processing payments, sending communications, and analysing
          data. These vendors are contractually obligated to protect your
          information and use it only for the purposes we specify.
        </p>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Business clients:
          </strong>{" "}
          If you are a caller or end user whose information was captured through
          a Gradia-powered business, that information is shared with the business
          that deployed the Gradia agent. Their use of your information is
          governed by their own privacy policy.
        </p>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Legal requirements:
          </strong>{" "}
          We may disclose information if required by law, court order, or
          government authority, or if we believe disclosure is necessary to protect
          our rights, your safety, or the safety of others.
        </p>
        <p className={`${body} mt-6`}>
          <strong className="font-semibold text-[#0A0A0A]">
            Business transfers:
          </strong>{" "}
          In the event of a merger, acquisition, or sale of assets, your
          information may be transferred as part of that transaction. We will
          notify you before your information is transferred and becomes subject to
          a different privacy policy.
        </p>

        <h2 className={h2}>4. Data Retention</h2>
        <p className={`${body} mt-6`}>
          We retain personal information for as long as necessary to provide our
          services and comply with legal obligations. Call recordings and
          transcripts are retained according to the retention settings configured
          by each business client. When you close your account, we will delete or
          anonymise your personal information within 90 days, unless we are
          required by law to retain it longer.
        </p>

        <h2 className={h2}>5. Data Security</h2>
        <p className={`${body} mt-6`}>
          We implement industry-standard security measures to protect your
          information, including encryption in transit and at rest, access
          controls, and regular security reviews. However, no method of
          transmission over the internet or electronic storage is 100% secure. We
          cannot guarantee absolute security and encourage you to use strong
          passwords and keep your account credentials confidential.
        </p>

        <h2 className={h2}>6. Healthcare Data and HIPAA</h2>
        <p className={`${body} mt-6`}>
          Gradia serves healthcare clients and may process Protected Health
          Information (PHI) as defined under the Health Insurance Portability and
          Accountability Act (HIPAA). Where applicable, Gradia enters into a
          Business Associate Agreement (BAA) with covered healthcare entities
          prior to handling PHI. If you are a healthcare provider using Gradia,
          please contact us to ensure appropriate agreements are in place.
        </p>

        <h2 className={h2}>7. Cookies and Tracking</h2>
        <p className={`${body} mt-6`}>
          We use cookies and similar technologies to operate our website,
          remember your preferences, and analyse traffic. You can control cookie
          settings through your browser. Disabling cookies may affect certain
          features of our website.
        </p>
        <p className={`${body} mt-6`}>We use the following types of cookies:</p>
        <ul className={`${list} mt-3`}>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">
              Essential cookies:
            </strong>{" "}
            Required for the website to function
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">
              Analytics cookies:
            </strong>{" "}
            Help us understand how visitors use our site
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">
              Marketing cookies:
            </strong>{" "}
            Used to deliver relevant content and track campaign performance
          </li>
        </ul>

        <h2 className={h2}>8. Your Rights</h2>
        <p className={`${body} mt-6`}>
          Depending on your location, you may have the following rights regarding
          your personal information:
        </p>
        <ul className={`${list} mt-3`}>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">Access:</strong>{" "}
            Request a copy of the personal information we hold about you
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">Correction:</strong>{" "}
            Request correction of inaccurate or incomplete information
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">Deletion:</strong>{" "}
            Request deletion of your personal information, subject to legal
            requirements
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">
              Portability:
            </strong>{" "}
            Request a machine-readable copy of your data
          </li>
          <li>
            <strong className="font-semibold text-[#0A0A0A]">Objection:</strong>{" "}
            Object to certain uses of your information, including marketing
          </li>
        </ul>
        <p className={`${body} mt-6`}>
          To exercise any of these rights, contact us at{" "}
          <a
            href="mailto:privacy@trygradia.com"
            className="text-[#3B6EF5] underline underline-offset-2 hover:opacity-90"
          >
            privacy@trygradia.com
          </a>
          . We will respond within 30 days.
        </p>

        <h2 className={h2}>9. Children&apos;s Privacy</h2>
        <p className={`${body} mt-6`}>
          Our services are not directed to individuals under the age of 18. We do
          not knowingly collect personal information from children. If you believe
          we have inadvertently collected information from a minor, please contact
          us immediately.
        </p>

        <h2 className={h2}>10. Changes to This Policy</h2>
        <p className={`${body} mt-6`}>
          We may update this Privacy Policy from time to time. When we make
          material changes, we will notify you by email or by posting a prominent
          notice on our website prior to the change taking effect. Your continued
          use of our services after the effective date constitutes acceptance of
          the updated policy.
        </p>

        <h2 className={h2}>11. Contact Us</h2>
        <p className={`${body} mt-6`}>
          If you have questions about this Privacy Policy or our data practices,
          please contact us:
        </p>
        <p className={`${body} mt-6`}>
          Gradia Inc.
          <br />
          Email:{" "}
          <a
            href="mailto:trygradia@gmail.com"
            className="text-[#3B6EF5] underline underline-offset-2 hover:opacity-90"
          >
            trygradia@gmail.com
          </a>
          <br />
          Website:{" "}
          <Link
            href="https://trygradia.com"
            className="text-[#3B6EF5] underline underline-offset-2 hover:opacity-90"
          >
            trygradia.com
          </Link>
        </p>
      </article>
    </div>
  );
}
